# Generated by Django 5.2.17 on 2026-09-27 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='Asia/Novosibirsk', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Открыто'), ('READY', 'На проверке'), ('CLOSED', 'Закрыто')], default='OPEN', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creation_started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('draft_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('BEFORE', 'До'), ('AFTER', 'После')], max_length=10)),
                ('original_path', models.CharField(max_length=255, unique=True)),
                ('preview_path', models.CharField(max_length=255, unique=True)),
                ('mime', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('SUBMIT', 'Отправка на проверку'), ('ACCEPT', 'Принятие'), ('RETURN', 'Возврат'), ('EDIT', 'Изменение')], max_length=10)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('result_status', models.CharField(blank=True, choices=[('OPEN', 'Открыто'), ('READY', 'На проверке'), ('CLOSED', 'Закрыто')], max_length=10, null=True)),
                ('result_version', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='issues.issue')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='issues.photo')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='issues.site')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.zone'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'BEFORE')), fields=('issue',), name='uq_one_before_photo_per_issue'),
        ),
        migrations.AddIndex(
            model_name='issueevent',
            index=models.Index(fields=['issue', 'created_at'], name='issues_issu_issue_i_5b5865_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uq_zone_site_name'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', 'due_date'], name='issues_issu_status_b94e80_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assignee', 'status'], name='issues_issu_assigne_68fa2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), ('closed_at__isnull', False)), models.Q(models.Q(('status', 'CLOSED'), _negated=True), ('closed_at__isnull', True)), _connector='OR'), name='closed_at_matches_status'),
        ),
    ]
