# Generated by Django 5.2.17 on 2026-09-28 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'замечание', 'verbose_name_plural': 'замечания'},
        ),
        migrations.AlterModelOptions(
            name='issueevent',
            options={'ordering': ['created_at'], 'verbose_name': 'событие замечания', 'verbose_name_plural': 'события замечаний'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'объект', 'verbose_name_plural': 'объекты'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'зона', 'verbose_name_plural': 'зоны'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_issues', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='закрыто'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='creation_started_at',
            field=models.DateTimeField(verbose_name='начало создания'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='draft_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID черновика'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateField(verbose_name='срок'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Открыто'), ('READY', 'На проверке'), ('CLOSED', 'Закрыто')], default='OPEN', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='изменено'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='версия'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.zone', verbose_name='зона'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Создание'), ('SUBMIT', 'Отправка на проверку'), ('ACCEPT', 'Принятие'), ('RETURN', 'Возврат'), ('EDIT', 'Изменение')], max_length=10, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='участник'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='issues.issue', verbose_name='замечание'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='new_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='стало'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='old_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='было'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='issues.photo', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='причина'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='request_hash',
            field=models.CharField(max_length=64, verbose_name='хеш запроса'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='request_id',
            field=models.UUIDField(unique=True, verbose_name='request_id'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='result_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Открыто'), ('READY', 'На проверке'), ('CLOSED', 'Закрыто')], max_length=10, null=True, verbose_name='итоговый статус'),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='result_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='итоговая версия'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='issues.issue', verbose_name='замечание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='kind',
            field=models.CharField(choices=[('BEFORE', 'До'), ('AFTER', 'После')], max_length=10, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='mime',
            field=models.CharField(max_length=50, verbose_name='MIME-тип'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original_path',
            field=models.CharField(max_length=255, unique=True, verbose_name='путь к оригиналу'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='preview_path',
            field=models.CharField(max_length=255, unique=True, verbose_name='путь к превью'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sha256',
            field=models.CharField(max_length=64, verbose_name='SHA-256'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='size_bytes',
            field=models.PositiveIntegerField(verbose_name='размер, байт'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='site',
            name='timezone',
            field=models.CharField(default='Asia/Novosibirsk', max_length=64, verbose_name='часовой пояс'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='issues.site', verbose_name='объект'),
        ),
    ]
