# Generated by Django 5.2.17 on 2026-09-28 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('issues', '0002_alter_issue_options_alter_issueevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logintoken',
            options={'verbose_name': 'токен входа', 'verbose_name_plural': 'токены входа'},
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='истекает'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='next_path',
            field=models.CharField(max_length=255, verbose_name='путь после входа'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='token_hash',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='хеш токена'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='использован'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ENGINEER', 'Инженер'), ('EXECUTOR', 'Исполнитель'), ('MANAGER', 'Руководитель')], max_length=20, null=True, verbose_name='предметная роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='issues.site', verbose_name='объект'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Участник узнаёт его, отправив боту /start', null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
