# Generated by Django 5.2.17 on 2026-09-27 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('next_offset', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BotDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('PHOTO', 'Фото'), ('ZONE', 'Зона'), ('DESCRIPTION', 'Описание'), ('ASSIGNEE', 'Исполнитель'), ('DUE_DATE', 'Срок'), ('CONFIRM', 'Подтверждение')], default='PHOTO', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
