# Generated by Django 5.2.17 on 2026-09-28 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botdraft',
            options={'verbose_name': 'черновик бота', 'verbose_name_plural': 'черновики бота'},
        ),
        migrations.AlterModelOptions(
            name='botstate',
            options={'verbose_name': 'состояние бота', 'verbose_name_plural': 'состояние бота'},
        ),
        migrations.AlterField(
            model_name='botdraft',
            name='expires_at',
            field=models.DateTimeField(verbose_name='истекает'),
        ),
        migrations.AlterField(
            model_name='botdraft',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='данные'),
        ),
        migrations.AlterField(
            model_name='botdraft',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='начат'),
        ),
        migrations.AlterField(
            model_name='botdraft',
            name='step',
            field=models.CharField(choices=[('PHOTO', 'Фото'), ('ZONE', 'Зона'), ('DESCRIPTION', 'Описание'), ('ASSIGNEE', 'Исполнитель'), ('DUE_DATE', 'Срок'), ('CONFIRM', 'Подтверждение')], default='PHOTO', max_length=20, verbose_name='шаг'),
        ),
        migrations.AlterField(
            model_name='botdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='изменён'),
        ),
        migrations.AlterField(
            model_name='botdraft',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_draft', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='botstate',
            name='next_offset',
            field=models.BigIntegerField(default=0, verbose_name='следующий offset'),
        ),
    ]
